### ISSUE TITLE
Manage the cart

### ISSUE THREAD

**Issue by Svinci131** [maxww/v-cab#19]

**Comment by ashes74** [comment]
- [ ] Add an item to the cart from product listing or product detail pages
- [ ] Remove an item from the cart
- [ ] Edit/update quantities of items in the cart
- [ ] Log in and continue editing the cart
- [ ] Refresh the page without being logged in and have the cart persist (you may use sessionStorage, localStorage, Cookies or JWT for this)

**Comment by ashes74** [comment]
I think I can write an interesting Angular version first, then do the routes...
