### ISSUE TITLE
order factory

### ISSUE THREAD

**Issue by ashes74** [maxww/v-cab#34]
required to connect the cart to:
- [x] cart page
- [ ] product page
- [ ] cart directive
- [ ] when clear cart, remove that order from database
- [ ] if not log in, we persist the cart in front end, if log in, we persist the cart in database(?)
  (so the non-logedIn users' carts persist based on the sessions)

**Comment by maxww** [comment]
- [ ] when clear cart, remove that order from database
- [ ] if not log in, we persist the cart in front end, if log in, we persist the cart in database(?)
(so the non-logedIn users' carts persist based on the sessions)

**Comment by ashes74** [comment]
@maxww  You might want to look at this when working on cart today.
